### ISSUE TITLE
Lock rotation axis?

### ISSUE THREAD

**Issue by 956MB** [frzi/Model3DView#1]
Is there currently a way to lock an axis of rotation? Like to only allow left-right rotation?

**Comment by frzi** [comment]
Hello 👋 

If you're talking about the `OrbitControls` then yes, most certainly! The initializer has [`minPitch` and `maxPitch`](https://github.com/frzi/Model3DView/blob/db0b54213208d573a93ec853830eac60844eda86/Sources/Model3DView/Camera/CameraControls.swift#L44). Just set both to `0` and you're good to go.
```swift
Model3DView(named: "robot.gltf")
	.cameraControls(OrbitControls(
		camera: $perspectiveCamera,
		minPitch: .degrees(0),
		maxPitch: .degrees(0)
	))
```

**Comment by 956MB** [comment]
@frzi Easy enough, thanks. I tried to do a similar thing with `minZoom: 0` and `maxZoom: 0` to disable the pinching to zoom, and my model is just gone, or is too far/little zoomed in. What's the correct way to disable pinch zoom but keep rotation and the set position on the model?

**Comment by frzi** [comment]
For zoom you want `1` for both min and max (or *anything* higher than `0`)

**Comment by 956MB** [comment]
@frzi Oh I see, I want to match the `minZoom` and `maxZoom` to my cameras z position, like how far back it is. I'm so dumb. Thanks.
