### ISSUE TITLE
Does Model3DView work with stl files?

### ISSUE THREAD

**Issue by 4rdhendu** [frzi/Model3DView#3]
Hi,

Very nice work! Does Model3DView work with .stl files. If no, what is a possible workaround? Also, how do we specify a path ("/var/xyz/test.stl") to the file we want to display if it resides at some known path?

**Comment by frzi** [comment]
Model3DView uses SceneKit and GLTFSceneKit under the hood. STL files are not supported. To support them, you'll need to find a package that converts STL to SceneKit, which you can then use using [init(scene:)](https://github.com/frzi/Model3DView/blob/de79951f2ee1ad888a7c61fcce57e13e5a6581f2/Sources/Model3DView/Model3DView.swift#L65). The supported file formats of SceneKit are [listed here](https://developer.apple.com/documentation/scenekit/scnscenesource).

To answer the second question (which is not relevant now), you can use [init(file:)](https://github.com/frzi/Model3DView/blob/de79951f2ee1ad888a7c61fcce57e13e5a6581f2/Sources/Model3DView/Model3DView.swift#L37) to initialize using a file that's not located inside the bundle.
