### ISSUE TITLE
Is this library still running?

### ISSUE THREAD

**Issue by 2dubu** [frzi/Model3DView#6]
`SCNView implements focusItemsInRect: - caching for linear focus movement is limited as long as this view is on screen.`

[Xcode 15.4, iOS 17.5] I had this error :(

**Comment by frzi** [comment]
Hmmm yes I get this warning as well when running on iOS 18 using the Xcode 16 beta. I'm not 100% certain what this entails. It still seems to be working as expected, however. But I'll keep an eye out on this. 😄

**Comment by 2dubu** [comment]
I see.. I'm sorry for the late confirmation. Can you tell me the simple example code that you ran?

**Comment by frzi** [comment]
I tried the `FancyIntroduction` example from [the examples repository](https://github.com/frzi/Model3DView-Examples). The warning appears in Xcode's logger, but everything seems to be working a-ok! 😄

**Comment by 2dubu** [comment]
Thank you for your answer 😁
