### ISSUE TITLE
How to make 3D model auto infinity horizontal rotating

### ISSUE THREAD

**Issue by abinhho** [frzi/Model3DView#8]
I tried to change camera to something like below but it does not works. 

```
@State var camera = PerspectiveCamera(position: .init(x: 0, y: 0, z: 10))
```

Please help.

**Comment by frzi** [comment]
Hmmm I'm not sure I understand your question exactly. You want the 3D model to rotate infinitely?

In this case you could use SwiftUI's [`TimelineView`](https://developer.apple.com/documentation/swiftui/timelineview) for an infinite animation and use the `date` to apply the rotation on the model.

```swift
@State private var camera = PerspectiveCamera(position: Vector3(x: 0, y: 0, z: 10))

var body: some View {
	TimelineView(.animation) { context in
		Model3DView(named: "Duck.glb")
			.transform(rotate: Euler(y: .radians(context.date.timeIntervalSince1970)))
			.camera(camera)
	}
}
```

Hope this helps 😄

**Comment by abinhho** [comment]
Thank you!!!

**Comment by abinhho** [comment]
I tested but model is not centered.
